name: Release Docker Container
on:
  workflow_dispatch:
  release:
    types: ["published"]

jobs:
  after-release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Info ${{ github.event.release }}, ${{ github.event.release.name }}, ${{ github.event.release.body }}"
  # docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: Build and push
  #       uses: docker/build-push-action@v5
  #       with:
  #         push: true
  #         tags: andrewdussstorable/dapr-cli:latest
  #         file: docker/Dockerfile